# Generated by Django 3.2.10 on 2022-06-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Ambassador', max_length=200)),
                ('desc', models.CharField(help_text='Enter description of Ambassador', max_length=200)),
            ],
        ),
    ]
