# Generated by Django 3.2.10 on 2022-06-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_events_workshops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Workshops',
            new_name='Workshop',
        ),
    ]
