# Generated by Django 3.2.10 on 2022-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220614_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='displayImage',
            field=models.ImageField(default='Pictures/Driver licence front.jpg', upload_to='Pictures/', verbose_name='Ambassador Image'),
        ),
    ]
