# Generated by Django 3.2.10 on 2022-06-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ambassador_displayimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='displayImage',
            field=models.ImageField(default=None, upload_to='Ambassador Image/', verbose_name='Ambassador Image'),
        ),
    ]
