# Generated by Django 3.2.10 on 2022-06-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220616_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='article',
            field=models.TextField(default=None),
        ),
    ]
