# Generated by Django 3.2.10 on 2022-06-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isFlagshipEvent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='article',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='startup',
            name='article',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='workshop',
            name='article',
            field=models.TextField(default=None),
        ),
    ]
