# Generated by Django 3.2.10 on 2022-06-17 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220617_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contentVideo',
            field=models.FileField(null=True, upload_to='Event Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.CreateModel(
            name='AmbassadorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('Ambassador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.ambassador')),
            ],
        ),
    ]
