# Generated by Django 3.2.10 on 2022-06-17 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220617_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contentVideo',
            field=models.FileField(null=True, upload_to='Project Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='startup',
            name='contentVideo',
            field=models.FileField(null=True, upload_to='StartUp Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='workshop',
            name='contentVideo',
            field=models.FileField(null=True, upload_to='Workshop Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
