# Generated by Django 3.2.10 on 2022-06-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='startup',
            name='link',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='workshop',
            name='link',
            field=models.URLField(default=None),
        ),
    ]
