# Generated by Django 4.0.5 on 2022-06-22 13:38

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220618_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='displayImage',
            field=models.ImageField(default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='AmbassadorImage/', verbose_name='Ambassador Image'),
        ),
    ]
