# Generated by Django 4.0.5 on 2022-06-23 02:04

import django.core.validators
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_ambassador_displayimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorimage',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contentVideo',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Event Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='event',
            name='displayImage',
            field=models.ImageField(default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Event Image/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contentVideo',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Project Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='displayImage',
            field=models.ImageField(default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Project Image/', verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='contentVideo',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='StartUp Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='displayImage',
            field=models.ImageField(default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='StartUp Image/', verbose_name='StartUp Image'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='contentVideo',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Workshop Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='displayImage',
            field=models.ImageField(default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Workshop Image/', verbose_name='Workshop Image'),
        ),
    ]
