# Generated by Django 4.0.5 on 2022-06-23 02:47

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ambassadorimage_image_alter_event_contentvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorimage',
            name='Ambassador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contentImages', to='api.ambassador'),
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/')),
                ('Event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contentImages', to='api.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='StartUpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/')),
                ('Event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contentImages', to='api.startup')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/')),
                ('Event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contentImages', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/')),
                ('Event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contentImages', to='api.event')),
            ],
        ),
    ]
